<a href="https://colab.research.google.com/github/CharulSawant/Natural-Language-Processing-NLP-Toolkit/blob/main/NLP1_text_to_vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

words = np.array([
    "I",
    "love",
    "AI",
    "love"
]).reshape(-1,1)

encoder = OneHotEncoder(sparse_output=False)

encoded = encoder.fit_transform(words)

print(encoded)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


one hot encoding

text to vector (vector is a numeric value) this numeric value is the data set conveted to biniary to let understand our machine

bag of words  BOW: counts how many times each word appears in a document.

        it is a good tree. it is a good plant. tree and plant are good

        good 3
        tree 2
        plant 2

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    "It is a good tree",
    "It is a good plant",
    "Tree and plant are good"
]

cv = CountVectorizer()

X = cv.fit_transform(corpus)

print(cv.get_feature_names_out())

print(X.toarray())

['and' 'are' 'good' 'is' 'it' 'plant' 'tree']
[[0 0 1 1 1 0 1]
 [0 0 1 1 1 1 0]
 [1 1 1 0 0 1 1]]


In [7]:
print(cv.vocabulary_)

{'it': 4, 'is': 3, 'good': 2, 'tree': 6, 'plant': 5, 'and': 0, 'are': 1}


N-Gram Model

Bag of Words only considers single words.

N-Gram considers groups of consecutive words.

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    "I love machine learning",
    "Machine learning is fun"
]

vectorizer = CountVectorizer(ngram_range=(2,2))

X = vectorizer.fit_transform(corpus)

print(vectorizer.get_feature_names_out())

print(X.toarray())

['is fun' 'learning is' 'love machine' 'machine learning']
[[0 0 1 1]
 [1 1 0 1]]
